# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

development:
  adapter: postgresql
  database: lixerr
  host: <%= ENV['IP'] %>
  username: hamza
  password: hamzaaltaf
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: lixerr
  host: <%= ENV['IP'] %>
  username: hamza
  password: hamzaaltaf
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: lixerr
  host: <%= ENV['IP'] %>
  username: hamza
  password: hamzaaltaf
  pool: 5
  timeout: 5000