# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

development:
  adapter: postgresql
  database: projectq_development
  host: <%= ENV['IP'] %>
  username: muqsitnawaz
  password: B.D.c00p3r
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: projectq_test
  host: <%= ENV['IP'] %>
  username: muqsitnawaz
  password: B.D.c00p3r
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: projectq_production
  pool: 5
  timeout: 5000